apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "irsa-manager.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: irsa-manager
    app.kubernetes.io/part-of: irsa-manager
    control-plane: controller-manager
  {{- include "irsa-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "irsa-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "irsa-manager.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.controllerManager.manager.args | nindent 8 }}
        command:
        - /manager
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: aws-secret
              optional: true
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: aws-secret
              optional: true
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              key: aws-session-token
              name: aws-secret
              optional: true
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              key: aws-region
              name: aws-secret
              optional: true
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              key: aws-role-arn
              name: aws-secret
              optional: true
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        {{- if .Values.proxy.enabled }}
        {{- if .Values.proxy.httpProxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy.httpProxy | quote }}
        {{- end }}
        {{- if .Values.proxy.httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy.httpsProxy | quote }}
        {{- end }}
        {{- if .Values.proxy.noProxy }}
        - name: NO_PROXY
          value: {{ .Values.proxy.noProxy | quote }}
        {{- end }}
      {{- end }}
        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag
          | default .Chart.AppVersion }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.controllerManager.manager.containerSecurityContext
          | nindent 10 }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "irsa-manager.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10